### ISSUE TITLE
PAPI integration or similar

### ISSUE THREAD

**Issue by eschnett** [Qthreads/qthreads#53]
I want to collect CPU hardware counter statistics in a Qthreads-parallelized program, e.g. via PAPI. Are there examples for doing so? Or is there general advice?

For example:
- How should I initialize PAPI? (per process, per thread?)
- Can I expect multiplexing to work reasonably?

**Comment by pmucci** [comment]
Hi.

Phil here, original author of PAPI back in ’95. ;-) I’ve been lurking on this list since I think Qthreads is very cool - and much needed. PAPI wants to work on a per-kernel-thread (aka pthread) instance. It has no means to measure ‘per-process’ (as the underlying substrate does not, except through inheritance). 

Are you looking to do instrumentation of code regions, overall counts of the entire execution, or counts of individual qthreads? If Qthreads can bounce from one underlying pthread to another (which would make sense), then one needs a way to make sure the counts follow the context. 

Multiplexing is a kernel level operation, so anything that works non-multiplexed, will work in this case…naturally your measurement granularity needs to be high enough. Consider cross posting this to the PAPI mailing list BTW.

Phil


Philip J. Mucci
Minimal Metrics LLC
Ph: +1.415.841.3577 | +46(0)72.172.2581
Fax: +1.415.689.3976  
www.minimalmetrics.com <http://www.minimalmetrics.com/>

**Comment by eschnett** [comment]
I am interested in measuring a code region that has been parallelized via Qthreads. For benchmarking, I can place barriers before and after the region, so that no unrelated threads will execute. I want to measure PAPI statistics across all hardware threads that execute.

When trying to do so, I often see negative numbers reported by PAPI. I assume this might be caused by execution threads jumping between hardware threads, confusing the PAPI readout. It might also be that PAPI is not properly initialized on each hardware thread. If this is so, then I would need access to low-level Qthreads features to call PAPI functions on hardware threads. I don't think this is currently supported.

**Comment by m3m0ryh0l3** [comment]
You can initialize PAPI on each HW thread (see https://github.com/Qthreads/qthreads/issues/52), but that's going to capture more than just your code region (naturally). You would need to stop PAPI collection every time your code region potentially-blocks, yields, or exits; and start PAPI collection every time your code region starts, un-blocks, or returns from a yield.

**Comment by pmucci** [comment]
Hi Erik,

If PAPI is not initialized on the threads then the read would error out, so it seems you’ve got that set. The negative numbers are a result of what you describe. I think the only way to do this is to run a start/stop (or a read/read) on all hardware threads before and after the computation. While not supported by QThreads, one might be able to special case the PAPI code to detect hardware thread and save PAPI state for each, thus could be checked again after the fact.
 

Philip J. Mucci
Minimal Metrics LLC
Ph: +1.415.841.3577 | +46(0)72.172.2581
Fax: +1.415.689.3976  
www.minimalmetrics.com <http://www.minimalmetrics.com/>

**Comment by npe9** [comment]
Hey @eschnett did you ever get this working?

**Comment by eschnett** [comment]
I stopped being interested in PAPI and am now using other tools, e.g. Linux `perf`.

**Comment by npe9** [comment]
@eschnett cool. If you see any performance bugs I'd love to see them.
