### ISSUE TITLE
How does performance compare to libdill ?

### ISSUE THREAD

**Issue by GuacheSuede** [Qthreads/qthreads#65]
http://libdill.org

**Comment by npe9** [comment]
Nobody's done any comparisons AFAIK, if you wanted to do an apples to apples comparison to Qthreads I'd try porting Unbalanced Tree Search (UTS) to libdill and using that as a baseline.

**Comment by npe9** [comment]
@m3m0ryh0l3 Looking at the API it looks like a reimplementation of Plan9's libthread aimed at webservers/sockets. Semantically  While the coroutines aren't allowed to interact via shared memory there are channel semantics and an alt operator ("choose") which provides Dijkstra's non-determinism construct without guards.

I doubt it poses any thread to qthreads from a performance perspective. It looks like signals are handled on a per coroutine basis, and channels are typically slower than mutices.

http://250bpm.com/blog:71 by the author of libdill seems to have an interesting comparison of the "structured concurrency" with go, the gist of the argument being that you want to have an implicit join to make sure both go out of scope at the same time.

Sadly the author doesn't understand guarded commands ("select considered harmful") and how they contribute to the understandability of a program from a logical perspective which is especially ironic because he's citing Dijkstra to complain about a programming language construct that Dijsktra himself made.

**Comment by GuacheSuede** [comment]
@sunstrik
